brew tap homebrew/autoupdate
brew tap homebrew/bundle
brew tap homebrew/services

brew install wget
brew install npm
brew install git
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting
brew install eza
brew install zoxide
brew install neovim
brew install tmux
brew install starship
brew install assh
brew install fastfetch
brew install zip
brew install unzip
brew install stow
brew install lazygit
brew install tpm
brew install bash
brew install bat
brew install docker
brew install gcc
brew install ffmpeg
brew install go
brew install mysql
brew install mysql@8.0
brew install neofetch
brew install node
brew install openjdk
brew install openvpn
brew install putty
brew install python@3.11
brew install rust
brew install tree
brew install luarocks
brew install lua@5.1
brew install btop
brew install clang
brew install lazydocker
brew install fzf
brew install gh
brew install gitui
brew install yazi
brew install vim-plug


cp -a . HomeDirectoryFiles/Linux/ ~/.
