return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons", "folke/todo-comments.nvim" },
  opts = {
    focus = false,
    auto_close = false,
    auto_open = false,
    auto_preview = true,
    auto_jump = { "lsp_definitions" },
    signs = {
      error = "󰅚 ",
      warning = "󰀪 ",
      hint = "󰌶 ",
      information = "󰋽 ",
      other = "󰗠 ",
    },
    use_diagnostic_signs = false,
    mode = "workspace_diagnostics", -- "workspace_diagnostics", "document_diagnostics", "quickfix", "lsp_references", "loclist"
    filter = { severity = vim.diagnostic.severity.ERROR }, -- filter diagnostics by severity
    action_keys = {
      close = "q",
      cancel = "<esc>",
      refresh = "r",
      jump = "<cr>",
      jump_close = { "o" },
      toggle_mode = "m",
      toggle_preview = "P",
      hover = "K",
      preview = "p",
      close_folds = { "zM", "zm" },
      open_folds = { "zR", "zr" },
      toggle_fold = { "zA", "za" },
      previous = "k",
      next = "j",
      help = "?",
    },
    indent_lines = true,
    win_config = { border = "single" },
    auto_fold = false,
    fold_open = "󰅀",
    fold_closed = "󰅂",
    group = true,
    padding = true,
    cycle_results = true,
    severity = nil,
    height = 10,
    width = 50,
    position = "bottom", -- bottom, top
    group_symbol = "  ",
    format = "{severity}: {message}",
    multiline = true,
    reverse = false,
    follow = false,
    title = true,
    header = true,
    icons = true,
    include_declaration = { "lsp_references", "lsp_implementations", "lsp_definitions" },
    scope = "cursor", -- cursor, file, workspace
    lang = nil,
    relative = "cursor", -- cursor, win, editor, root
    path_display = { "shorten" },
    code_action = {
      enable = true,
      extend = true,
    },
    open_no_results = true,
    line_format = "{severity_icon} {message}",
    fold_closed = "󰅂",
    fold_open = "󰅀",
  },
  cmd = "Trouble",
  keys = {
    { "<leader>xx", "<cmd>Trouble diagnostics toggle<CR>", desc = "Open trouble diagnostics" },
    { "<leader>xw", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", desc = "Open trouble workspace diagnostics" },
    { "<leader>xd", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", desc = "Open trouble document diagnostics" },
    { "<leader>xq", "<cmd>Trouble quickfix toggle<CR>", desc = "Open trouble quickfix list" },
    { "<leader>xl", "<cmd>Trouble loclist toggle<CR>", desc = "Open trouble location list" },
    { "<leader>xt", "<cmd>Trouble todo toggle<CR>", desc = "Open todos in trouble" },
    { "<leader>xs", "<cmd>Trouble symbols toggle<CR>", desc = "Open trouble symbols" },
    { "<leader>xr", "<cmd>Trouble lsp_references toggle<CR>", desc = "Open trouble LSP references" },
    { "<leader>xf", "<cmd>Trouble lsp_definitions toggle<CR>", desc = "Open trouble LSP definitions" },
    { "<leader>xi", "<cmd>Trouble lsp_implementations toggle<CR>", desc = "Open trouble LSP implementations" },
    { "<leader>xtd", "<cmd>Trouble lsp_type_definitions toggle<CR>", desc = "Open trouble LSP type definitions" },
  },
}